-- lesson_target_skills
-- AUTO-GENERATED from packages/core by scripts/gen-seeds.ts — do not edit by hand.
insert into lesson_target_skills (lesson_id, skill_id, weight) values
  ('basic.greetings_intro', 'fn.greetings', 1),
  ('basic.greetings_intro', 'fn.self_intro', 1),
  ('basic.greetings_intro', 'gr.present_simple', 1),
  ('basic.daily_routine', 'lex.daily_routine', 1),
  ('basic.daily_routine', 'gr.present_simple', 1),
  ('basic.daily_routine', 'gr.prep_time', 1),
  ('basic.ordering_food', 'lex.food', 1),
  ('basic.ordering_food', 'fn.make_requests', 1),
  ('basic.ordering_food', 'gr.modal_permission', 1),
  ('basic.shopping', 'lex.shopping_money', 1),
  ('basic.shopping', 'gr.comparatives', 1),
  ('basic.shopping', 'fn.make_requests', 1),
  ('basic.directions', 'fn.give_directions', 1),
  ('basic.directions', 'gr.prep_movement', 1),
  ('basic.directions', 'gr.imperatives', 1),
  ('basic.articles_fix', 'gr.articles', 1),
  ('basic.articles_fix', 'gr.countability', 1),
  ('basic.stative_fix', 'gr.stative_verbs', 1),
  ('basic.stative_fix', 'gr.present_continuous', 1),
  ('inter.interview_intro', 'lex.interview', 1),
  ('inter.interview_intro', 'fn.self_intro', 1),
  ('inter.interview_intro', 'gr.present_perfect', 1),
  ('inter.workplace_meeting', 'lex.meetings', 1),
  ('inter.workplace_meeting', 'fn.give_opinion', 1),
  ('inter.workplace_meeting', 'fn.agree', 1),
  ('inter.phone_support', 'lex.telephone', 1),
  ('inter.phone_support', 'lex.customer_support', 1),
  ('inter.phone_support', 'fn.clarify', 1),
  ('inter.storytelling', 'fn.narrate_past_event', 1),
  ('inter.storytelling', 'gr.past_simple', 1),
  ('inter.storytelling', 'gr.past_continuous', 1),
  ('inter.opinions', 'fn.give_opinion', 1),
  ('inter.opinions', 'fn.justify_opinion', 1),
  ('inter.opinions', 'gr.subordinating_conjunctions', 1),
  ('adv.presentation', 'fn.signpost_presentation', 1),
  ('adv.presentation', 'fn.summarize', 1),
  ('adv.presentation', 'ph.word_stress', 1),
  ('adv.negotiation', 'lex.sales', 1),
  ('adv.negotiation', 'fn.disagree_politely', 1),
  ('adv.negotiation', 'fn.hedge', 1),
  ('adv.conditionals', 'gr.conditional_second', 1),
  ('adv.conditionals', 'gr.conditional_third', 1)
on conflict (lesson_id, skill_id) do update set weight = excluded.weight;
