-- skills
-- AUTO-GENERATED from packages/core by scripts/gen-seeds.ts — do not edit by hand.
insert into skills (id, family, label, cefr, cluster, difficulty, prerequisites, exemplar, detectors) values
  ('gr.present_simple', 'grammar', 'Present simple', 'A1', 'Tenses', 0.1, ARRAY[]::text[], 'I work in a bank.', '[]'::jsonb),
  ('gr.present_continuous', 'grammar', 'Present continuous', 'A1', 'Tenses', 0.15, ARRAY['gr.present_simple']::text[], 'I am working now.', '[]'::jsonb),
  ('gr.past_simple', 'grammar', 'Past simple', 'A2', 'Tenses', 0.25, ARRAY['gr.present_simple']::text[], 'I worked yesterday.', '[]'::jsonb),
  ('gr.past_continuous', 'grammar', 'Past continuous', 'A2', 'Tenses', 0.3, ARRAY['gr.past_simple']::text[], 'I was working at 9 pm.', '[]'::jsonb),
  ('gr.present_perfect', 'grammar', 'Present perfect', 'B1', 'Tenses', 0.45, ARRAY['gr.past_simple','gr.present_simple']::text[], 'I have lived here for five years.', '[]'::jsonb),
  ('gr.present_perfect_continuous', 'grammar', 'Present perfect continuous', 'B2', 'Tenses', 0.62, ARRAY['gr.present_perfect']::text[], 'I have been waiting for an hour.', '[]'::jsonb),
  ('gr.past_perfect', 'grammar', 'Past perfect', 'B2', 'Tenses', 0.65, ARRAY['gr.past_simple','gr.present_perfect']::text[], 'The bus had left before I arrived.', '[]'::jsonb),
  ('gr.future_will', 'grammar', 'Future with will', 'A2', 'Tenses', 0.28, ARRAY['gr.present_simple']::text[], 'I will call you tomorrow.', '[]'::jsonb),
  ('gr.future_going_to', 'grammar', 'Future with going to', 'A2', 'Tenses', 0.3, ARRAY['gr.present_continuous']::text[], 'I am going to start a course.', '[]'::jsonb),
  ('gr.future_continuous', 'grammar', 'Future continuous', 'B2', 'Tenses', 0.63, ARRAY['gr.future_will','gr.present_continuous']::text[], 'I will be travelling next week.', '[]'::jsonb),
  ('gr.articles', 'grammar', 'Articles (a / an / the)', 'A1', 'Articles & determiners', 0.18, ARRAY[]::text[], 'I am a doctor.', '[]'::jsonb),
  ('gr.zero_article', 'grammar', 'Zero article', 'B1', 'Articles & determiners', 0.42, ARRAY['gr.articles']::text[], 'Life is short.', '[]'::jsonb),
  ('gr.demonstratives', 'grammar', 'Demonstratives (this/that/these/those)', 'A1', 'Articles & determiners', 0.12, ARRAY[]::text[], 'This is my bag.', '[]'::jsonb),
  ('gr.quantifiers', 'grammar', 'Quantifiers (some/any/much/many)', 'A2', 'Articles & determiners', 0.3, ARRAY[]::text[], 'I have some questions.', '[]'::jsonb),
  ('gr.possessives', 'grammar', 'Possessives (my/your/his)', 'A1', 'Articles & determiners', 0.14, ARRAY[]::text[], 'That is her phone.', '[]'::jsonb),
  ('gr.prep_time', 'grammar', 'Prepositions of time (in/on/at)', 'A2', 'Prepositions', 0.26, ARRAY[]::text[], 'The meeting is at 3 pm on Monday.', '[]'::jsonb),
  ('gr.prep_place', 'grammar', 'Prepositions of place (in/on/at)', 'A1', 'Prepositions', 0.18, ARRAY[]::text[], 'The keys are on the table.', '[]'::jsonb),
  ('gr.prep_movement', 'grammar', 'Prepositions of movement (to/into/through)', 'A2', 'Prepositions', 0.3, ARRAY[]::text[], 'I walked to the station.', '[]'::jsonb),
  ('gr.prep_dependent', 'grammar', 'Dependent prepositions (depend on, good at)', 'B2', 'Prepositions', 0.68, ARRAY[]::text[], 'It depends on the weather.', '[]'::jsonb),
  ('gr.word_order', 'grammar', 'Word order (Subject-Verb-Object)', 'A1', 'Sentence structure', 0.16, ARRAY[]::text[], 'I speak English.', '[]'::jsonb),
  ('gr.subject_verb_agreement', 'grammar', 'Subject-verb agreement', 'A2', 'Sentence structure', 0.3, ARRAY['gr.present_simple']::text[], 'She works hard.', '[]'::jsonb),
  ('gr.there_is_are', 'grammar', 'There is / there are', 'A1', 'Sentence structure', 0.15, ARRAY[]::text[], 'There are two options.', '[]'::jsonb),
  ('gr.question_formation', 'grammar', 'Question formation', 'A1', 'Sentence structure', 0.2, ARRAY[]::text[], 'Where do you work?', '[]'::jsonb),
  ('gr.negation', 'grammar', 'Negation', 'A1', 'Sentence structure', 0.18, ARRAY[]::text[], 'I don''t agree.', '[]'::jsonb),
  ('gr.countability', 'grammar', 'Countable & uncountable nouns', 'A2', 'Sentence structure', 0.32, ARRAY[]::text[], 'I need some information.', '[]'::jsonb),
  ('gr.modal_ability', 'grammar', 'Modals of ability (can/could)', 'A1', 'Modals', 0.18, ARRAY[]::text[], 'I can drive.', '[]'::jsonb),
  ('gr.modal_permission', 'grammar', 'Modals of permission (can/may)', 'A2', 'Modals', 0.3, ARRAY[]::text[], 'May I come in?', '[]'::jsonb),
  ('gr.modal_obligation', 'grammar', 'Modals of obligation (must/have to)', 'B1', 'Modals', 0.44, ARRAY[]::text[], 'I have to leave now.', '[]'::jsonb),
  ('gr.modal_possibility', 'grammar', 'Modals of possibility (might/could)', 'B1', 'Modals', 0.48, ARRAY[]::text[], 'It might rain later.', '[]'::jsonb),
  ('gr.modal_advice', 'grammar', 'Modals of advice (should/ought to)', 'B1', 'Modals', 0.45, ARRAY[]::text[], 'You should rest.', '[]'::jsonb),
  ('gr.conditional_zero', 'grammar', 'Zero conditional', 'A2', 'Conditionals', 0.34, ARRAY['gr.present_simple']::text[], 'If you heat ice, it melts.', '[]'::jsonb),
  ('gr.conditional_first', 'grammar', 'First conditional', 'B1', 'Conditionals', 0.46, ARRAY['gr.future_will','gr.present_simple']::text[], 'If it rains, I will stay home.', '[]'::jsonb),
  ('gr.conditional_second', 'grammar', 'Second conditional', 'B2', 'Conditionals', 0.64, ARRAY['gr.past_simple']::text[], 'If I had time, I would travel.', '[]'::jsonb),
  ('gr.conditional_third', 'grammar', 'Third conditional', 'C1', 'Conditionals', 0.82, ARRAY['gr.past_perfect']::text[], 'If I had known, I would have called.', '[]'::jsonb),
  ('gr.gerund_infinitive', 'grammar', 'Gerund vs infinitive', 'B1', 'Verb patterns', 0.5, ARRAY[]::text[], 'I enjoy reading; I want to learn.', '[]'::jsonb),
  ('gr.phrasal_verbs', 'grammar', 'Phrasal verbs', 'B1', 'Verb patterns', 0.52, ARRAY[]::text[], 'Please turn off the light.', '[]'::jsonb),
  ('gr.stative_verbs', 'grammar', 'Stative verbs', 'A2', 'Verb patterns', 0.33, ARRAY['gr.present_continuous']::text[], 'I know the answer.', '[]'::jsonb),
  ('gr.passive_voice', 'grammar', 'Passive voice', 'B2', 'Verb patterns', 0.66, ARRAY['gr.past_simple','gr.present_perfect']::text[], 'The report was sent yesterday.', '[]'::jsonb),
  ('gr.reported_speech', 'grammar', 'Reported speech', 'B2', 'Verb patterns', 0.68, ARRAY['gr.past_simple']::text[], 'She said she was busy.', '[]'::jsonb),
  ('gr.comparatives', 'grammar', 'Comparatives', 'A2', 'Comparison', 0.28, ARRAY[]::text[], 'This is cheaper than that.', '[]'::jsonb),
  ('gr.superlatives', 'grammar', 'Superlatives', 'A2', 'Comparison', 0.32, ARRAY['gr.comparatives']::text[], 'It is the best option.', '[]'::jsonb),
  ('gr.coordinating_conjunctions', 'grammar', 'Coordinating conjunctions (and/but/so)', 'A2', 'Connectors', 0.26, ARRAY[]::text[], 'I tried, but it failed.', '[]'::jsonb),
  ('gr.subordinating_conjunctions', 'grammar', 'Subordinating conjunctions (because/although)', 'B1', 'Connectors', 0.48, ARRAY[]::text[], 'I left because I was tired.', '[]'::jsonb),
  ('gr.relative_clauses', 'grammar', 'Relative clauses (who/which/that)', 'B1', 'Connectors', 0.52, ARRAY['gr.question_formation']::text[], 'The man who called is my boss.', '[]'::jsonb),
  ('gr.imperatives', 'grammar', 'Imperatives', 'A1', 'Sentence structure', 0.14, ARRAY[]::text[], 'Please sit down.', '[]'::jsonb),
  ('fn.greetings', 'function', 'Greetings', 'A1', 'Social functions', 0.08, ARRAY[]::text[], 'Good morning! How are you?', '[]'::jsonb),
  ('fn.self_intro', 'function', 'Introducing yourself', 'A1', 'Social functions', 0.12, ARRAY[]::text[], 'Hi, I am Ravi from Chennai.', '[]'::jsonb),
  ('fn.small_talk', 'function', 'Small talk', 'A2', 'Social functions', 0.3, ARRAY[]::text[], 'How was your weekend?', '[]'::jsonb),
  ('fn.leave_taking', 'function', 'Closing a conversation', 'A1', 'Social functions', 0.12, ARRAY[]::text[], 'It was nice talking to you.', '[]'::jsonb),
  ('fn.express_gratitude', 'function', 'Expressing gratitude', 'A1', 'Social functions', 0.1, ARRAY[]::text[], 'Thank you so much for your help.', '[]'::jsonb),
  ('fn.apologize', 'function', 'Apologising', 'A2', 'Social functions', 0.28, ARRAY[]::text[], 'I am sorry for the delay.', '[]'::jsonb),
  ('fn.make_requests', 'function', 'Making requests', 'A2', 'Getting things done', 0.3, ARRAY[]::text[], 'Could you please repeat that?', '[]'::jsonb),
  ('fn.ask_for_help', 'function', 'Asking for help', 'A1', 'Getting things done', 0.18, ARRAY[]::text[], 'Can you help me with this?', '[]'::jsonb),
  ('fn.give_directions', 'function', 'Giving directions', 'A2', 'Getting things done', 0.34, ARRAY[]::text[], 'Go straight and turn left.', '[]'::jsonb),
  ('fn.make_suggestions', 'function', 'Making suggestions', 'B1', 'Getting things done', 0.44, ARRAY[]::text[], 'Why don''t we meet at noon?', '[]'::jsonb),
  ('fn.complain_politely', 'function', 'Complaining politely', 'B2', 'Getting things done', 0.66, ARRAY[]::text[], 'I am afraid there is a problem with my order.', '[]'::jsonb),
  ('fn.check_understanding', 'function', 'Checking understanding', 'A2', 'Getting things done', 0.3, ARRAY[]::text[], 'Do you mean the morning slot?', '[]'::jsonb),
  ('fn.give_opinion', 'function', 'Giving an opinion', 'B1', 'Opinions & discussion', 0.42, ARRAY[]::text[], 'In my opinion, remote work helps.', '[]'::jsonb),
  ('fn.justify_opinion', 'function', 'Justifying an opinion', 'B1', 'Opinions & discussion', 0.5, ARRAY['fn.give_opinion']::text[], 'I think so because it saves time.', '[]'::jsonb),
  ('fn.agree', 'function', 'Agreeing', 'A2', 'Opinions & discussion', 0.3, ARRAY[]::text[], 'That is a good point.', '[]'::jsonb),
  ('fn.disagree_politely', 'function', 'Disagreeing politely', 'B1', 'Opinions & discussion', 0.52, ARRAY['fn.give_opinion']::text[], 'I see your point, but I disagree.', '[]'::jsonb),
  ('fn.express_preference', 'function', 'Expressing preference', 'A2', 'Opinions & discussion', 0.34, ARRAY[]::text[], 'I would rather take the bus.', '[]'::jsonb),
  ('fn.compare_options', 'function', 'Comparing options', 'B1', 'Opinions & discussion', 0.5, ARRAY[]::text[], 'The first plan is better value.', '[]'::jsonb),
  ('fn.hedge', 'function', 'Hedging / softening', 'B2', 'Opinions & discussion', 0.7, ARRAY[]::text[], 'It might be a good idea, perhaps.', '[]'::jsonb),
  ('fn.clarify', 'function', 'Clarifying', 'A2', 'Managing conversation', 0.32, ARRAY[]::text[], 'Sorry, could you clarify that?', '[]'::jsonb),
  ('fn.paraphrase', 'function', 'Paraphrasing', 'B2', 'Managing conversation', 0.64, ARRAY['fn.clarify']::text[], 'So what you mean is...', '[]'::jsonb),
  ('fn.interrupt_politely', 'function', 'Interrupting politely', 'B1', 'Managing conversation', 0.52, ARRAY[]::text[], 'Sorry to interrupt, but...', '[]'::jsonb),
  ('fn.turn_take', 'function', 'Taking turns', 'B1', 'Managing conversation', 0.46, ARRAY[]::text[], 'Go ahead, please.', '[]'::jsonb),
  ('fn.repair', 'function', 'Self-repair', 'B1', 'Managing conversation', 0.48, ARRAY[]::text[], 'I mean, I went there last week.', '[]'::jsonb),
  ('fn.tag_questions', 'function', 'Tag questions', 'A2', 'Managing conversation', 0.33, ARRAY['gr.question_formation']::text[], 'You''re coming, aren''t you?', '[]'::jsonb),
  ('fn.narrate_past_event', 'function', 'Narrating a past event', 'B1', 'Extended speaking', 0.48, ARRAY['gr.past_simple']::text[], 'Last year I attended an interview...', '[]'::jsonb),
  ('fn.describe_person', 'function', 'Describing a person', 'A2', 'Extended speaking', 0.32, ARRAY[]::text[], 'My manager is calm and helpful.', '[]'::jsonb),
  ('fn.describe_place', 'function', 'Describing a place', 'A2', 'Extended speaking', 0.32, ARRAY[]::text[], 'My town is small but busy.', '[]'::jsonb),
  ('fn.summarize', 'function', 'Summarising', 'B2', 'Extended speaking', 0.64, ARRAY[]::text[], 'To sum up, we agreed on two points.', '[]'::jsonb),
  ('fn.signpost_presentation', 'function', 'Signposting a presentation', 'B2', 'Extended speaking', 0.7, ARRAY['fn.summarize']::text[], 'First I will cover... then...', '[]'::jsonb),
  ('fn.telephone_open_close', 'function', 'Opening & closing a phone call', 'A2', 'Extended speaking', 0.34, ARRAY[]::text[], 'Hello, this is Priya from support.', '[]'::jsonb),
  ('lex.daily_routine', 'lexis', 'Daily routine vocabulary', 'A1', 'Vocabulary clusters', 0.12, ARRAY[]::text[], 'I wake up at six and get ready.', '[]'::jsonb),
  ('lex.family', 'lexis', 'Family vocabulary', 'A1', 'Vocabulary clusters', 0.1, ARRAY[]::text[], 'I live with my parents and sister.', '[]'::jsonb),
  ('lex.food', 'lexis', 'Food & dining vocabulary', 'A1', 'Vocabulary clusters', 0.14, ARRAY[]::text[], 'I would like a masala dosa, please.', '[]'::jsonb),
  ('lex.shopping_money', 'lexis', 'Shopping & money vocabulary', 'A2', 'Vocabulary clusters', 0.28, ARRAY[]::text[], 'How much does this cost?', '[]'::jsonb),
  ('lex.travel_directions', 'lexis', 'Travel & directions vocabulary', 'A2', 'Vocabulary clusters', 0.3, ARRAY[]::text[], 'Which platform is the train on?', '[]'::jsonb),
  ('lex.workplace', 'lexis', 'Workplace vocabulary', 'B1', 'Vocabulary clusters', 0.46, ARRAY[]::text[], 'I will send the deck after the standup.', '[]'::jsonb),
  ('lex.interview', 'lexis', 'Job interview vocabulary', 'B1', 'Vocabulary clusters', 0.5, ARRAY[]::text[], 'My key strength is problem solving.', '[]'::jsonb),
  ('lex.customer_support', 'lexis', 'Customer support vocabulary', 'B1', 'Vocabulary clusters', 0.48, ARRAY[]::text[], 'May I place you on a short hold?', '[]'::jsonb),
  ('lex.telephone', 'lexis', 'Telephone vocabulary', 'A2', 'Vocabulary clusters', 0.34, ARRAY[]::text[], 'Could you speak a little louder?', '[]'::jsonb),
  ('lex.health', 'lexis', 'Health vocabulary', 'A2', 'Vocabulary clusters', 0.32, ARRAY[]::text[], 'I have a headache since morning.', '[]'::jsonb),
  ('lex.emotions', 'lexis', 'Emotions vocabulary', 'A2', 'Vocabulary clusters', 0.3, ARRAY[]::text[], 'I felt nervous before the test.', '[]'::jsonb),
  ('lex.numbers_time', 'lexis', 'Numbers & time vocabulary', 'A1', 'Vocabulary clusters', 0.1, ARRAY[]::text[], 'The class starts at quarter past nine.', '[]'::jsonb),
  ('lex.weather', 'lexis', 'Weather vocabulary', 'A1', 'Vocabulary clusters', 0.14, ARRAY[]::text[], 'It is hot and humid today.', '[]'::jsonb),
  ('lex.education', 'lexis', 'Education vocabulary', 'A2', 'Vocabulary clusters', 0.3, ARRAY[]::text[], 'I completed my degree in commerce.', '[]'::jsonb),
  ('lex.technology', 'lexis', 'Technology vocabulary', 'B1', 'Vocabulary clusters', 0.48, ARRAY[]::text[], 'The app crashed after the update.', '[]'::jsonb),
  ('lex.banking', 'lexis', 'Banking vocabulary', 'B1', 'Vocabulary clusters', 0.5, ARRAY[]::text[], 'I want to open a savings account.', '[]'::jsonb),
  ('lex.transport', 'lexis', 'Transport vocabulary', 'A2', 'Vocabulary clusters', 0.28, ARRAY[]::text[], 'The auto fare is metered.', '[]'::jsonb),
  ('lex.hobbies', 'lexis', 'Hobbies vocabulary', 'A1', 'Vocabulary clusters', 0.16, ARRAY[]::text[], 'In my free time I play cricket.', '[]'::jsonb),
  ('lex.clothing', 'lexis', 'Clothing vocabulary', 'A1', 'Vocabulary clusters', 0.16, ARRAY[]::text[], 'I am looking for a cotton shirt.', '[]'::jsonb),
  ('lex.housing', 'lexis', 'Housing vocabulary', 'A2', 'Vocabulary clusters', 0.3, ARRAY[]::text[], 'The flat has two bedrooms.', '[]'::jsonb),
  ('lex.meetings', 'lexis', 'Meetings vocabulary', 'B2', 'Vocabulary clusters', 0.66, ARRAY[]::text[], 'Let us park that and move on.', '[]'::jsonb),
  ('lex.sales', 'lexis', 'Sales vocabulary', 'B2', 'Vocabulary clusters', 0.66, ARRAY[]::text[], 'This plan offers the best value for you.', '[]'::jsonb),
  ('lex.email_to_speech', 'lexis', 'Turning email into speech', 'B2', 'Vocabulary clusters', 0.64, ARRAY[]::text[], 'I am calling to follow up on my email.', '[]'::jsonb),
  ('lex.government_office', 'lexis', 'Government office vocabulary', 'B1', 'Vocabulary clusters', 0.5, ARRAY[]::text[], 'I need to renew my license.', '[]'::jsonb),
  ('lex.social_media', 'lexis', 'Social & online vocabulary', 'A2', 'Vocabulary clusters', 0.3, ARRAY[]::text[], 'I will share the link in the group.', '[]'::jsonb),
  ('ph.v_w_distinction', 'phoneme', 'Distinguishing /v/ and /w/', 'A2', 'Consonant sounds', 0.3, ARRAY[]::text[], 'very vs water', '[]'::jsonb),
  ('ph.theta_voiceless', 'phoneme', 'Voiceless TH /θ/', 'B1', 'Consonant sounds', 0.44, ARRAY[]::text[], 'think, three, month', '[]'::jsonb),
  ('ph.eth_voiced', 'phoneme', 'Voiced TH /ð/', 'B1', 'Consonant sounds', 0.46, ARRAY[]::text[], 'this, that, mother', '[]'::jsonb),
  ('ph.z_s', 'phoneme', 'Distinguishing /z/ and /s/', 'A2', 'Consonant sounds', 0.34, ARRAY[]::text[], 'zip vs sip', '[]'::jsonb),
  ('ph.zh', 'phoneme', 'The /ʒ/ sound', 'B2', 'Consonant sounds', 0.64, ARRAY[]::text[], 'vision, measure', '[]'::jsonb),
  ('ph.retroflex_t_d', 'phoneme', 'Alveolar (not retroflex) /t/ /d/', 'A2', 'Consonant sounds', 0.36, ARRAY[]::text[], 'time, day', '[]'::jsonb),
  ('ph.ship_sheep', 'phoneme', 'Short /ɪ/ vs long /iː/', 'A2', 'Vowel sounds', 0.34, ARRAY[]::text[], 'ship vs sheep', '[]'::jsonb),
  ('ph.cat_cut', 'phoneme', 'Distinguishing /æ/ and /ʌ/', 'A2', 'Vowel sounds', 0.34, ARRAY[]::text[], 'cat vs cut', '[]'::jsonb),
  ('ph.schwa', 'phoneme', 'The schwa /ə/', 'B1', 'Vowel sounds', 0.5, ARRAY[]::text[], 'about, banana', '[]'::jsonb),
  ('ph.cluster_initial', 'phoneme', 'Initial consonant clusters', 'B1', 'Connected speech', 0.48, ARRAY[]::text[], 'school (not is-school)', '[]'::jsonb),
  ('ph.cluster_final', 'phoneme', 'Final consonant clusters', 'B1', 'Connected speech', 0.5, ARRAY[]::text[], 'asked, texts', '[]'::jsonb),
  ('ph.p_f', 'phoneme', 'Distinguishing /p/ and /f/', 'A2', 'Consonant sounds', 0.32, ARRAY[]::text[], 'pan vs fan', '[]'::jsonb),
  ('ph.sh_s', 'phoneme', 'Distinguishing /ʃ/ and /s/', 'A2', 'Consonant sounds', 0.34, ARRAY[]::text[], 'she vs see', '[]'::jsonb),
  ('ph.word_stress', 'phoneme', 'Word stress', 'B1', 'Stress & rhythm', 0.5, ARRAY[]::text[], 'PHO-to-graph vs pho-TO-gra-phy', '[]'::jsonb),
  ('ph.sentence_stress', 'phoneme', 'Sentence stress', 'B2', 'Stress & rhythm', 0.64, ARRAY[]::text[], 'I NEVER said that.', '[]'::jsonb),
  ('ph.rhythm_stress_timed', 'phoneme', 'Stress-timed rhythm', 'B2', 'Stress & rhythm', 0.7, ARRAY[]::text[], 'reducing weak syllables', '[]'::jsonb),
  ('ph.final_consonant_voicing', 'phoneme', 'Final consonant voicing', 'B1', 'Connected speech', 0.48, ARRAY[]::text[], 'bag (not back)', '[]'::jsonb),
  ('ph.silent_letters', 'phoneme', 'Silent letters', 'A2', 'Consonant sounds', 0.34, ARRAY[]::text[], 'know, hour, half', '[]'::jsonb),
  ('ph.intonation_questions', 'phoneme', 'Question intonation', 'B1', 'Stress & rhythm', 0.46, ARRAY[]::text[], 'rising tone on yes/no questions', '[]'::jsonb),
  ('ph.linking', 'phoneme', 'Linking & connected speech', 'B2', 'Connected speech', 0.66, ARRAY[]::text[], 'an_apple, turn_it_off', '[]'::jsonb)
on conflict (id) do update set
  family = excluded.family, label = excluded.label, cefr = excluded.cefr, cluster = excluded.cluster,
  difficulty = excluded.difficulty, prerequisites = excluded.prerequisites, exemplar = excluded.exemplar,
  detectors = excluded.detectors;
