/**
 * Builds packages/core/src/conversation/lessons.data.ts from:
 *   1. the current lessons (preserved verbatim, ids never change) and
 *   2. the E7 authoring workflow output (scenario `variants` for existing lessons +
 *      brand-new lessons per unit).
 *
 * Deterministic + validated so the course content is reproducible and reviewable.
 *
 * Usage: node scripts/build-lessons.mjs <authored-workflow-output.json> [current.json]
 *   <authored-workflow-output.json> — the Workflow result file (has .result.units)
 *   [current.json]                  — defaults to /tmp/speakwell-lessons-current.json
 */
import { readFileSync, writeFileSync } from 'node:fs';

const authoredPath = process.argv[2];
const currentPath = process.argv[3] ?? '/tmp/speakwell-lessons-current.json';
if (!authoredPath) {
  console.error('usage: node scripts/build-lessons.mjs <authored.json> [current.json]');
  process.exit(1);
}

const current = JSON.parse(readFileSync(currentPath, 'utf8')); // { [unitId]: { unit, lessons } }
const rawAuthored = JSON.parse(readFileSync(authoredPath, 'utf8'));
const authoredUnits = (rawAuthored.result?.units ?? rawAuthored.units ?? rawAuthored).reduce((m, u) => {
  m[u.unitId] = u;
  return m;
}, {});

const FIELD_ORDER = ['id', 'unitId', 'levelId', 'title', 'fn', 'canDo', 'phrases', 'scenario', 'variants', 'l1Note'];
const ordered = (o) => {
  const out = {};
  for (const k of FIELD_ORDER) if (o[k] !== undefined) out[k] = o[k];
  return out;
};

const errors = [];
const seenIds = new Set();
const final = [];
let enriched = 0;
let added = 0;

for (const unitId of Object.keys(current)) {
  const { unit, lessons } = current[unitId];
  const authored = authoredUnits[unitId] ?? { enrich: [], newLessons: [] };
  const enrichById = new Map((authored.enrich ?? []).map((e) => [e.id, e.variants]));

  // 1) existing lessons, preserved; attach variants if authored.
  for (const l of lessons) {
    const variants = enrichById.get(l.id);
    const merged = { ...l };
    if (Array.isArray(variants) && variants.length) {
      merged.variants = [...(l.variants ?? []), ...variants];
      enriched++;
    }
    if (seenIds.has(merged.id)) errors.push(`duplicate id ${merged.id}`);
    seenIds.add(merged.id);
    final.push(ordered(merged));
  }

  // 2) new lessons for this unit.
  for (const n of authored.newLessons ?? []) {
    const id = `${unitId}-${n.slug}`;
    if (seenIds.has(id)) {
      errors.push(`new lesson collides with existing id ${id}`);
      continue;
    }
    if (!Array.isArray(n.phrases) || n.phrases.length < 5 || n.phrases.length > 8)
      errors.push(`${id}: phrases must be 5–8 (got ${n.phrases?.length})`);
    if (!n.scenario) errors.push(`${id}: missing scenario`);
    seenIds.add(id);
    added++;
    final.push(
      ordered({
        id,
        unitId,
        levelId: unit.levelId,
        title: n.title,
        fn: n.fn,
        canDo: n.canDo,
        phrases: n.phrases,
        scenario: n.scenario,
        variants: n.variants && n.variants.length ? n.variants : undefined,
        l1Note: n.l1Note || undefined,
      }),
    );
  }
}

if (errors.length) {
  console.error('VALIDATION ERRORS:\n' + errors.map((e) => '  - ' + e).join('\n'));
  process.exit(1);
}

const banner =
  '/**\n' +
  ' * The course lesson data. AUTO-GENERATED by scripts/build-lessons.mjs — do not hand-edit.\n' +
  ' * Existing lesson ids are preserved across regenerations so saved progress never breaks.\n' +
  ' */\n' +
  "import type { Lesson } from './curriculum.js';\n\n";
const body = `export const LESSONS: Lesson[] = ${JSON.stringify(final, null, 2)};\n`;
const outPath = new URL('../packages/core/src/conversation/lessons.data.ts', import.meta.url);
writeFileSync(outPath, banner + body);

console.log(`✅ wrote ${final.length} lessons (${enriched} enriched with variants, ${added} new) → lessons.data.ts`);
const withVariants = final.filter((l) => l.variants?.length).length;
console.log(`   ${withVariants}/${final.length} lessons have ≥1 scenario variant`);
